services:
  web:
    image: 112639119087.dkr.ecr.eu-north-1.amazonaws.com/flask-mysql:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw